import torch
import torch.nn as nn
from einops import rearrange
from torchvision.transforms import GaussianBlur

from module import GELU, MRF, ChannelAttention, InitialBlock


class UpdateT(nn.Module):
    """
    Update module for auxiliary variable T in the unfolding framework.

    Args:
        lambda_1 (float): Trade-off parameter in the formulation.
        mu (float): ADMM penalty parameter.
        dim (int): Number of hyperspectral channels.
    """

    def __init__(self, lambda_1: float, mu: float, dim: int) -> None:
        super().__init__()

        self.lambda_1 = lambda_1
        self.mu = mu

        self.proj = nn.Sequential(
            nn.Conv2d(
                in_channels=dim,
                out_channels=dim,
                kernel_size=5,
                padding=2,
                groups=6,
            ),
            ChannelAttention(endmember=dim),
        )

    def forward(self, f_a: torch.Tensor, u: torch.Tensor) -> torch.Tensor:
        """
        Args:
            f_a: Feature tensor generated by Dnet(A), shape (B, C, H, W).
            u: Dual variable, shape (B, C, H, W).

        Returns:
            Updated T tensor, shape (B, C, H, W).
        """
        residual = f_a - u
        t = (self.lambda_1 + self.mu * residual) / (self.lambda_1 + self.mu)
        return self.proj(t)


class UpdateA(nn.Module):
    """
    Update module for variable A in the unfolding framework.

    Args:
        lambda_2 (float): Trade-off parameter in the formulation.
        mu (float): ADMM penalty parameter.
        dim (int): Number of hyperspectral channels.
        s_channel (int): Number of Sentinel-2 bands.
    """

    def __init__(
        self,
        lambda_2: float,
        mu: float,
        dim: int,
        s_channel: int = 12,
    ) -> None:
        super().__init__()

        self.lambda_2 = lambda_2
        self.mu = mu

        self.blurring = GaussianBlur(kernel_size=7, sigma=0.7)
        self.adjblur = nn.Sequential(MRF(dim=s_channel))
        self.proj = nn.Sequential(nn.Linear(dim, dim), GELU())

        self.d_transform = nn.Conv2d(
            in_channels=s_channel,
            out_channels=dim,
            kernel_size=1,
            padding=0,
        )

        self.grad_attn_1 = nn.Sequential(ChannelAttention(endmember=dim))
        self.grad_attn_2 = nn.Sequential(ChannelAttention(endmember=dim))
        self.grad_attn_3 = nn.Sequential(ChannelAttention(endmember=dim))

        self.lr = nn.Parameter(torch.randn(1, dim, 1, 1))

    def forward(
        self,
        a: torch.Tensor,
        grad_3: torch.Tensor,
        s_u: torch.Tensor,
        d_matrix: torch.Tensor,
        p: torch.Tensor,
    ) -> torch.Tensor:
        """
        Args:
            a: Current estimate of hyperspectral output, shape (B, dim, H, W).
            grad_3: Gradient feature of discriminator, shape (B, dim, H, W).
            s_u: PriorNet output, i.e., spatial-resolution-unified Sentinel-2 data,
                shape (B, s_channel, H, W).
            d_matrix: Learnable spectral response matrix, shape (s_channel, dim).
            p: Spectral prior matrix, shape (B, dim, dim).

        Returns:
            Updated A tensor, shape (B, dim, H, W).
        """
        a_blur = self.blurring(a)

        d_a_blur = d_matrix @ rearrange(a_blur, "b c h w -> b c (h w)")
        d_a_blur = rearrange(d_a_blur, "b c (h w) -> b c h w", h=a.shape[-2])

        a_2d = rearrange(a, "b c h w -> b c (h w)")

        grad_1 = self.d_transform(self.adjblur(d_a_blur)) - self.d_transform(
            self.adjblur(s_u)
        )

        gram = a_2d @ a_2d.permute(0, 2, 1)
        spec_corr = self.proj(gram)
        p = self.proj(p)

        grad_2 = -2 * self.lambda_2 * (spec_corr @ a_2d - p @ a_2d)
        grad_2 = rearrange(grad_2, "b c (h w) -> b c h w", h=a.shape[-2])

        grad_1 = self.grad_attn_1(grad_1 / (grad_1.norm() + 1e-8))
        grad_2 = self.grad_attn_2(grad_2 / (grad_2.norm() + 1e-8))
        grad_3 = self.grad_attn_3(grad_3 / (grad_3.norm() + 1e-8))

        grad_total = grad_1 + grad_2 + grad_3
        a = a - self.lr.exp() * grad_total

        return a


class UALNet(nn.Module):
    """
    Unfolding-based model for Sentinel-2 to AVIRIS-level reconstruction.

    Inputs:
        1. s_u:
            Output of PriorNet, i.e., spatial-resolution-unified Sentinel-2 data.
            Shape: (B, s_channel, H, W)

        2. dnet:
            A given discriminator in unfolding procedure to provide
            gradient-based features, i.e., unfolding adversarial learning. 

        3. p:
            Spectral prior matrix estimated using PriorNet.
            Shape: (B, dim, dim)

    Args:
        lambda_1 (float): Trade-off parameter for discriminator-maximization regularization (DMR).
        lambda_2 (float): Trade-off parameter for the spectral prior regularization.
        mu (float):  Quasi-Split Bregman (QSB) penalty parameter.
        dim (int): Number of output hyperspectral bands.
        s_channel (int): Number of Sentinel-2 bands.
        num_iter (int): Number of unfolded QSB iterations.
    """

    def __init__(
        self,
        lambda_1: float,
        lambda_2: float,
        mu: float,
        dim: int,
        s_channel: int = 12,
        num_iter: int = 2,
    ) -> None:
        super().__init__()

        self.lambda_1 = lambda_1
        self.lambda_2 = lambda_2
        self.mu = mu
        self.dim = dim
        self.s_channel = s_channel
        self.num_iter = num_iter

        self.initial = InitialBlock(
            in_channels=s_channel,
            out_channels=dim,
            num_blocks=10,
        )

        self.blocks = nn.ModuleList()
        self.d_matrix = nn.Parameter(torch.ones(s_channel, dim))

        for _ in range(num_iter):
            self.blocks.append(
                nn.ModuleList(
                    [
                        UpdateT(lambda_1=lambda_1, mu=mu, dim=dim),
                        UpdateA(
                            lambda_2=lambda_2,
                            mu=mu,
                            dim=dim,
                            s_channel=s_channel,
                        ),
                    ]
                )
            )

    def forward(
        self,
        s_u: torch.Tensor,
        dnet: nn.Module,
        p: torch.Tensor,
    ) -> torch.Tensor:
       
        a = self.initial(s_u)
        u = torch.zeros_like(a)

        for update_t, update_a in self.blocks:
            f_a = dnet(a)
            t = update_t(f_a, u)

            loss = self.mu * 0.5 * torch.sum((f_a - t - u) ** 2)
            grad_3, = torch.autograd.grad(loss, a, create_graph=True)

            a = update_a(a, grad_3, s_u, self.d_matrix, p)
            u = u - (dnet(a) - t)

        return a


if __name__ == "__main__":
    from D_net import Discriminator

    print("=" * 60)
    print("UALNet Quick Test")
    print("=" * 60)

    device = "cuda" if torch.cuda.is_available() else "cpu"

    batch_size = 1
    s_channel = 12
    dim = 186
    height = 64
    width = 64

    s_u = torch.randn(batch_size, s_channel, height, width, device=device)
    p = torch.randn(batch_size, dim, dim, device=device)

    dnet = Discriminator(in_channels=dim, hidden_channels=15).to(device)
    model = UALNet(
        lambda_1=5e-4,
        lambda_2=0.5,
        mu=0.05,
        dim=dim,
        s_channel=s_channel,
        num_iter=2,
    ).to(device)

    model.eval()
    dnet.eval()

    with torch.enable_grad():
        output = model(s_u, dnet, p)

    print(f"Input S_u shape : {tuple(s_u.shape)}")
    print(f"Input P shape   : {tuple(p.shape)}")
    print(f"Output shape    : {tuple(output.shape)}")

    total_params = sum(p.numel() for p in model.parameters())
    print(f"UALNet params: {total_params:,}")
    print("Quick test finished successfully.")
